feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView, FollowingView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
    path('following/', FollowingView.as_view(), name='following')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from django.conf import settings
from django.conf.urls.static import static

# url is depreciated, so we use re_path instead

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
    path('', include(profiles_urls, namespace='profiles')),
    re_path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


## if settings.DEBUG:
##    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path("profile/<str:username>/", views.ProfileDetailView.as_view(), name='profile'),
    path("profile/<str:username>/follow", views.FollowView.as_view(), name='follow'),
]

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length = 140, blank = False, null = False)
    image = ImageField()
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.text

followers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Follower(models.Model):
    followed_by = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name='followed_by'
    )
    following = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        related_name='following'
    )

    def __str__(self) -> str:
        return f"{self.followed_by.id} is following {self.following.id}"
    
    class Meta:
        unique_together = ('followed_by', 'following',)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        # when delete user, also delete profile
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = ImageField(upload_to='profiles', default='profiles/IMG_3686.jpeg')

    def __str__(self):
        return self.user.username

## signal
@receiver(post_save, sender=User)    

def create_user_profile(sender, instance, created, **kwargs):
    ### Create a new Profile() object when a Django User is created
    if created:
        Profile.objects.create(user=instance)

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()
    text = forms.CharField(label="Description")

feed/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from followers.models import Follower

# Create your views here.
class HomePageView(TemplateView):
    template_name = "feed/home.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        ## order by id descending: minus sign 
        context['posts'] = Post.objects.all().order_by('-id')
        return context
    
class PostDetailView(DetailView):
    template_name = "feed/detail.html"
    model = Post

class AddPostView(LoginRequiredMixin, FormView):
    template_name = "feed/new_post.html"
    form_class = PostForm
    success_url = "/"

    ## IMPORTANT: Use this when you need to get "request"
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)
        
    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image'],
            author = self.request.user
        )
        messages.add_message(self.request, messages.SUCCESS, "Your post was successful")
        return super().form_valid(form)
    
class FollowingView(LoginRequiredMixin, TemplateView):
    template_name = "feed/home.html"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        following = list(Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True))

        ## order by id descending: minus sign 
        context['posts'] = Post.objects.filter(author__in=following).order_by('-id')
        return context

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import View, DetailView
from django.contrib.auth.models import User
from feed.models import Post
from followers.models import Follower
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from followers.models import Follower

# Create your views here.
class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context["total_posts"] = Post.objects.filter(author=user).count()
        context["posts_by_user"] = Post.objects.filter(author=user).order_by('-id')
        context["total_followers"] = Follower.objects.filter(following=user).count()
        context["total_following"] = Follower.objects.filter(followed_by=user).count()
        
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context
        
class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")
        
        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")
        
        if data['action'] == "follow":
            # follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # unfollow
            try:
                follower = Follower.objects.get(
                followed_by=request.user,
                following=other_user
            )
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

feed/templates/feed/detail.html
{% extends "base.html" %}
{% block title %}Detail view{% endblock %}
{% load thumbnail %}

{% block content %}
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-3">
            <img src="{{ object.image.url }}" class="img-fluid rounded">
            <hr>
            <p>
                {% thumbnail post.author.profile.image "45x45" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
                &nbsp;<a href="{% url 'profiles:profile' post.author.username %}" style="color:#000000; text-decoration:none">{{ post.author.username }}</a>
            </p>
            <p>{{object.text}}</p>
            <p>{{object.date | date:"F j, Y, g:i:a"}}<p>
        </div>
    </div>
    
{% endblock %}

feed/templates/feed/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
Home
{% endblock%}

{% block content %} 

    <div class="row">
        {% for post in posts %}
            <div class="col-sm-6 col-md-3">
                <div class="card my-4">
                    <p class="card-text px-3 pt-3">
                        {% thumbnail post.author.profile.image "45x45" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                        &nbsp;<a href="{% url 'profiles:profile' post.author.username %}" style="color:#000000; text-decoration:none">{{ post.author.username }}</a>
                    </p>
                    {% thumbnail post.image "300x300" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                    {% endthumbnail %}

                    <div class="card-body">
                    <p class="card-text">{{ post.text }}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-sm-6 offset-3 text-center py-5 my-5">
                <h3>Welcome!</h3>
                <p>Add your first image?</p>
                <a href="{% url "feed:post" %}" class="btn btn-lg btn-success">Upload Image</a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

feed/templates/feed/new_post.html
{% extends "base.html" %}
{% block title %}Upload a new image{% endblock %}

{% block content %}
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        <h2>Upload a new image!</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button type="submit" class="btn btn-lg btn-success">Submit form</button>
        </div>
    </form>
{% endblock %}

profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
Profile - {{ user.username }}
{% endblock%}

{% block content %} 
<!--profile bar-->
  <section class="h-100 gradient-custom-2">
    <div class="container py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xxl-12">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: #333333; height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <img src="{{ user.profile.image.url }}"
                  alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                  style="width: 150px; z-index: 1">
                {% if request.user.is_authenticated %}
                {% if request.user != user %}
                <button type="button" class="btn btn-outline-dark js-follow" data-mdb-ripple-color="dark"
                  style="z-index: 1;" data-username="{{ user.username }}" 
                  data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}">
                  <div class="js-follow-text">
                    {% if you_follow %}
                    Unfollow
                    {% else %}
                    Follow
                    {% endif %}
                  </div>
                </button>
                {% endif %}
                {% endif %}
              </div>
              <div class="ms-3" style="margin-top: 130px;">
                <h5>{{ user.username }}</h5>
              </div>
            </div>
            <div class="p-4 text-black" style="background-color: #f8f9fa;">
              <div class="d-flex justify-content-end text-center py-1">
                <div>
                  <p class="mb-1 h5">{{ total_posts }}</p>
                  <p class="small text-muted mb-0">Photos</p>
                </div>
                <div class="px-3">
                  <p class="mb-1 h5">{{ total_followers }}</p>
                  <p class="small text-muted mb-0">Followers</p>
                </div>
                <div>
                  <p class="mb-1 h5">{{ total_following }}</p>
                  <p class="small text-muted mb-0">Following</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<!-- posts -->
<div class="row">
    {% for post in posts_by_user %}
        <div class="col-sm-6 col-md-3">
            <div class="card my-4">
                {% thumbnail post.image "300x300" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}

                <div class="card-body">
                <p class="card-text">{{ post.text }}</p>
                <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="col-sm-6 offset-3 text-center py-5 my-5">
            <h3>Welcome!</h3>
            <p>Add your first image?</p>
            <a href="{% url "feed:post" %}" class="btn btn-lg btn-success">Upload Image</a>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Image Sharer{% endblock%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        {% include "includes/navbar.html" %}

        {% if messages %}
            {% for message in messages %}
                <div class="bg-{% if message.tags %}{{message.tags}}{% else %}success{% endif %} bg-gradient text-center text-white py-4">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="container">
            {% block content %} {% endblock %}
        </div>

        <!-- modal: does not show up by default -->
        <div class="modal" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Modal body text goes here.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>          
          
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Sharer</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:following' %}">Following</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profiles:profile' request.user.username %}">My Photos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post' %}">Add new image</a>
          </li>
          <li class="nav-item">   
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">   
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          <li class="nav-item">   
            <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
          </li>
          {% endif %}
      </div>
    </div>
  </nav>